runtime: java
api_version: '1.0'
env: flex
#env: standard
#threadsafe: true
runtime_config:
  jdk: openjdk8
liveness_check:
  initial_delay_sec: '300'
  check_interval_sec: '30'
  timeout_sec: '4'
  failure_threshold: 4
  success_threshold: 2
#liveness_check:
#  path: ""
readiness_check:
  check_interval_sec: '5'
  timeout_sec: '4'
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: '1800'
#service_account: iconic-computer-368714@appspot.gserviceaccount.com
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5